### ISSUE TITLE
Players from a cracked version of the game can not join.

### ISSUE THREAD

**Issue by TecnoBruh** [LionariusPy/SkinRestorer#2]
My friends play with online-mode=false because they don't have a minecraft account, with this mod on the server they can't join and get the "invalid name" error, but the server isn't in online mode. I can join because I have a minecraft account, and the moment I deleted this mod from the server they could join.

**Comment by LionariusPy** [comment]
fixed in https://github.com/LionariusPy/SkinRestorer/commit/eb2b81612c26f680056bb21a53a89acc1b18ec13
